spring:
  application:
    name: auth-identity-service

  config:
    import:
      - "optional:configserver:http://localhost:8888"
      - "optional:configserver:http://localhost:8888/common-properties.yml"
