spring:
  application:
    name: config-server-service

  profiles:
    active: dev       # <--- AUTO-ACTIVATE DEV PROFILE
    group:
      dev: native
      stg: native
      prd: native

  cloud:
    config:
      server:
        git:
          enabled: false
        native:
          search-locations:
            - classpath:/configurations/{profile}
            - file:./configurations/{profile}

server:
  port: 8888
